### ISSUE TITLE
Build failure on Linux due to case sensitivity in paths

### ISSUE THREAD

**Issue by mihaly044** [JKamsker/LiteDB.Migration#1]
#### Description
When attempting to build the project on a Linux environment using the provided solution file (`LiteDb.Migration.sln`), the build process fails.  

The failure is due to a mismatch in the case of certain directory names. Specifically, the solution file references directories as `LiteDB.Migration*` (with uppercase "DB"), but the actual directories in the repository are named `LiteDb.Migration*` (with lowercase "b"). This discrepancy leads to a failure in locating the referenced project directories on case-sensitive filesystems like those in Linux.

#### Environment:
- OS: Debian 12
- .NET SDK version: 8.0.200

#### Steps to reproduce:
1. Clone the repository to a Linux machine.
2. Navigate to the root directory of the cloned repository.
3. Execute `dotnet build` in the solution directory.
4. The build fails with errors indicating that the project files `LiteDB.Migration*` directories cannot be found.

#### Expected behavior:
The `dotnet build` command should locate all project files and build the solution without errors.

#### Actual behavior:
The build process fails on Linux due to the case sensitivity of the filesystem not matching the casing of the paths specified in the solution file.

```bash
$> dotnet build
MSBuild version 17.9.4+90725d08d for .NET
/usr/share/dotnet/sdk/8.0.200/NuGet.targets(414,5): error MSB3202: The project file "/home/misi/LiteDB.Migration/LiteDB.Migration.Console/LiteDB.Migration.ConsoleTest.csproj" was not found. [/home/misi/LiteDB.Migration/LiteDb.Migration.sln]
/usr/share/dotnet/sdk/8.0.200/NuGet.targets(414,5): error MSB3202: The project file "/home/misi/LiteDB.Migration/LiteDB.Migration/LiteDB.Migration.csproj" was not found. [/home/misi/LiteDB.Migration/LiteDb.Migration.sln]
/usr/share/dotnet/sdk/8.0.200/NuGet.targets(414,5): error MSB3202: The project file "/home/misi/LiteDB.Migration/LiteDB.Migration.Tests/LiteDB.Migration.Tests.csproj" was not found. [/home/misi/LiteDB.Migration/LiteDb.Migration.sln]

Build FAILED.

/usr/share/dotnet/sdk/8.0.200/NuGet.targets(414,5): error MSB3202: The project file "/home/misi/LiteDB.Migration/LiteDB.Migration.Console/LiteDB.Migration.ConsoleTest.csproj" was not found. [/home/misi/LiteDB.Migration/LiteDb.Migration.sln]
/usr/share/dotnet/sdk/8.0.200/NuGet.targets(414,5): error MSB3202: The project file "/home/misi/LiteDB.Migration/LiteDB.Migration/LiteDB.Migration.csproj" was not found. [/home/misi/LiteDB.Migration/LiteDb.Migration.sln]
/usr/share/dotnet/sdk/8.0.200/NuGet.targets(414,5): error MSB3202: The project file "/home/misi/LiteDB.Migration/LiteDB.Migration.Tests/LiteDB.Migration.Tests.csproj" was not found. [/home/misi/LiteDB.Migration/LiteDb.Migration.sln]
    0 Warning(s)
    3 Error(s)
```

**Comment by JKamsker** [comment]
Thanks for the fix :)
+10 internet points for you 🚀
